
testbuild: &testbuild
  working_directory: ~/repo
  docker:
    - image: node:9

deployjob: &deployjob
  working_directory: ~/repo
  docker:
    - image: ubuntu:16.04

usecache: &usecache
  - checkout
  - restore_cache:
      keys:
        - v1-dependencies-{{ checksum "package.json" }}
        - v1-dependencies-
  - run: yarn install
  - save_cache:
      paths:
        - node_modules
      key: v1-dependencies-{{ checksum "package.json" }}

version: 2
jobs:
  test:
    <<: *testbuild
    steps:
      <<: *usecache
      - run: yarn test

  build:
    <<: *testbuild
    steps:
      <<: *usecache
      - run: yarn build
      - run: mkdir temp && mv dist temp/dist && cp package.json temp/package.json
      - persist_to_workspace:
          root: temp
          paths:
            - dist
            - package.json

  deploy_dev:
    <<: *deployjob
    steps:
      - attach_workspace:
          at: temp
      - add_ssh_keys:
          fingerprints:
            - "51:36:2c:23:29:e8:0b:03:a0:a9:b7:70:38:b1:35:9c"
      - run:
          name: deploy to dev
          command: |
            cd temp && rsync -a ./ deploy@dappnews.jujiyangasli.com:/home/deploy/dist/

workflows:
  version: 2
  build_deploy:
    jobs:
      - test
      - build:
          filters:
            branches:
              only:
                develop
          context: circle-dev
      - deploy_dev:
          filters:
            branches:
              only:
                develop
          requires:
            - build

